server:
  port: 9000
#  ssl:
#    key-store: F:\Intel\gpnews\data-file\src\main\resources\keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: tomcat

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gpnews?useSSL=false&amp;characterEncoding=utf-8&amp;useUnicode=true
    username: sa
    password: 123456
  redis:
    host: 127.0.0.1
    password:
    database: 1
    jedis:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 8
    timeout: 3000
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

file-upload:
  base: C://gpnews
